### PR TITLE
Fix commenting issue

### PR DESCRIPTION
**Pull request by afeinstein20**
There was an issue with the comments on Lines 730-757. I've fixed this issue for future tess-point updates :)

### CODE REVIEW

**Comment by christopherburke** [comment]
Thanks.  I broke my own code!  Learn me to commit without testing.  Poor form on my part.

**Comment by christopherburke** [comment]
Still broken with some whitespace.  I will update another fix.

**Comment by afeinstein20** [comment]
It happens to everyone! Thanks for fixing it so quickly :)

**Comment by christopherburke** [comment]
It appears to be fixed in v0.3.5 update with pip.  Let me know if stil having problems.

**Pull request merged**
